### PR TITLE
 add GetBuildConsole method. Update sdk & framework version.

### PR DESCRIPTION
**Pull request by idoop**
1. add GetBuildConsole method.
2. update sdk version.
3. update TargetFramework version.
4. update test.

### CODE REVIEW

**Comment by idoop** [comment]
It's done.:blush:

**Comment by alanedwardes** [comment]
Sure, apologies I didn’t pick this up again - will get it pushed this evening UTC!

**Comment by idoop** [comment]
ok,thank you.

**Comment by alanedwardes** [comment]
Not sure what happened with the previous build, it reported that the NuGet push was successful but there was nothing on nuget.org. Anyway... it's there now!

https://www.nuget.org/packages/Narochno.Jenkins/3.0.0

**Pull request merged**
